### ISSUE TITLE
Duration/dismiss after + global dismiss

### ISSUE THREAD

**Issue by pgawlowski** [teodorpatras/EasyTipView#106]
It would be nice to have feature like `show(duration:)` with dismiss after duration.

Additionally it would be nice to have global `dismiss` and `popActivity`.

Dismiss to hide every visible Tip, `popActivity` to dismiss last activity.

Is it possible to check values like `isVisible`?

**Comment by teodorpatras** [comment]
This can be achieved by keeping a reference to the view and doing with it whatever you please, whenever you please.
