### ISSUE TITLE
Swift 4 

### ISSUE THREAD

**Issue by zoufishanmehdi** [teodorpatras/EasyTipView#108]
Hi, is EasyTipView compatible with Swift 4? Thank you.

**Comment by LucasR93** [comment]
No, throws some errors when compiling

**Comment by zoufishanmehdi** [comment]
@LucasR93 I see. Thank you

**Comment by igorkislyuk** [comment]
What about [this](https://github.com/teodorpatras/EasyTipView/pull/109)?

**Comment by nawar** [comment]
Yeah, Swift 4 please or merge @igorkislyuk PR

**Comment by alijaza** [comment]
Any updates on this?
