### ISSUE TITLE
Please forget about "private", "fileprivate" and etc keywords if you develop a public library

### ISSUE THREAD

**Issue by gerchicov-bp** [teodorpatras/EasyTipView#120]
`contentSize` is declared as private lazy variable. It is totally incorrect but ok, I'll try to override `draw(_:)` method...

`draw(_:)` is public but uses `drawBorder(_:context:)` and `drawText(_:context:)` which are private. If I try to override them too they access to private methods/variables too. So I just wanted to change `bubbleVInset` value and redraw but it seems I must rewrite the half of the library just because someone likes use "private" and similar keywords

**Comment by teodorpatras** [comment]
amazing attitude; keep it up! it will get you far in life.

✌️ and ❤️
