### ISSUE TITLE
EasyTipView not getting added to leftBarButtonItem in navigation bar

### ISSUE THREAD

**Issue by zoufishanmehdi** [teodorpatras/EasyTipView#123]
Hi, I'm trying to show easyTipView for leftBarButtonItem in navigation bar. I used the following code before and it was working fine, but it no longer seems to work:

` let text = "Tap button to dismiss"
   let tipView = EasyTipView(text: sideMenuText, preferences: setPreferences(), delegate: self)
   tipView.show(animated: true, forItem: self.navigationItem.leftBarButtonItem!, withinSuperView: nil)`

Any ideas? Would really appreciate your help.

**Comment by giann** [comment]
Same issue. Within `tipView.show(animated: true, forItem: self.navigationItem.leftBarButtonItem!, withinSuperView: nil)` it tries to access `item.view` which is `nil`
