### ISSUE TITLE
Having trouble dismissing?

### ISSUE THREAD

**Issue by TravelNVal** [teodorpatras/EasyTipView#13]
New to swift, so having trouble understanding how to dismiss the tooltip.  I have it so when i click a button the tool tip displays, which it does.  But will not dismiss.  Thought to create a check variable for when the tool tip is displayed and the button is tapped again it is dismissed, but not working.

    @IBAction func whyAction(sender: AnyObject) {
        let easy = EasyTipView(text: "Your privacy is respected per our Privacy Policy", preferences: EasyTipView.Preferences.init(), delegate: self)
        if tipViewStart == 0 {
            easy.showForView(sender as! UIView, withinSuperview: nil, animated: true)
            tipViewStart = 1
        } else {
            easy.dismissWithCompletion(nil)
            tipViewStart = 0
        }
      }

Just an update, didn't realize you had to click the tooltip to have it disappear... duh on my part.  But nevertheless, can i dismiss by clicking on the button?

**Comment by teodorpatras** [comment]
you are trying to dismiss a newly created instance. This is not about being new to Swift. Try having a permanent reference to your ``EasyTipView`` and dismiss that one, not the one that you create 4 lines above the dismiss command.
