### ISSUE TITLE
support swift 4.1

### ISSUE THREAD

**Issue by IsmailHassanein** [teodorpatras/EasyTipView#133]
The current version is showing few syntax errors when I updated my Xcode. please update the code to swift 4.1

**Comment by IsmailHassanein** [comment]
HI @hungphat812, sorry I didn't figure out what is the problem from the crash report and the code. I'm not an expert here. I just use it. I suggest you find some other one that is not abandoned. I will do the same at some point too.

**Comment by hungphat812** [comment]
Thank you for reply. 👍

**Comment by llyons** [comment]
When will EasyTipView be converted for swift 4.1.  We are also getting syntax errors.  We have to specifically change the swift language version for EasyTipView to 3.3 (xcode 9.4.1) to get this to build.

Also is there a way to set the swift version for this POD after doing gem install cocoapods, pod setup, pod install that doesnt involve a human in xcode ui?

We are trying to get this working in a full CI build.  All of the other PODs we use are ok with 4.1

**Comment by IsmailHassanein** [comment]
This repo seems to be abandoned. the last commit was 10 months ago. you can look in the forks for someone having and updated version or you just add the source code to your project manually and fix  it yourself. 

regarding the setting the swift version by pods you can do that in podfile. please check this [example](https://stackoverflow.com/questions/40501440/how-to-set-the-legacy-swift-version-for-each-pod-in-podfile-xcode-9-0-swift-3-2).

**Comment by llyons** [comment]
Thanks that does the trick.. much appreciated.

**Comment by drbarto** [comment]
@llyons would you mind sharing your solution -- especially if you found a fork that's in good shape?

**Comment by teodorpatras** [comment]
Version 2.0.0 has been released with support for Swift 4.
