### ISSUE TITLE
Feature Request : drop shadow / Shadow under tooltip

### ISSUE THREAD

**Issue by AalokParikh** [teodorpatras/EasyTipView#134]
Is it possible to show shadow like we have when we use` UIView.layer.shadow`?
We have tried to give or add show for the contex using this code 
        
        let shadow = APPCOLOR.Pink.cgColor
        let shadowOffset = CGSize(width: 5.0, height: 5.0)
        let shadowBlurRadius: CGFloat = 5
        context.setShadow(offset:shadowOffset , blur:shadowBlurRadius, color: shadow)

But no success. Please guide me for the same.

**Comment by danillla** [comment]
I've added shadow to tooltip like this

tipView = EasyTipView(text: tipAddress, preferences: self.preferences)
tipView.layer.shadowColor = UIColor.black.cgColor
tipView.layer.shadowOffset = CGSize(width: 0.0, height: 2.0)
tipView.layer.shadowRadius = 2.0
tipView.layer.shadowOpacity = 0.7
tipView.show(animated:false, forView: self.centerPin, withinSuperview: self.view)

Hope this helps.

**Comment by teodorpatras** [comment]
shadow support is available as of v`2.0.3`
