### ISSUE TITLE
Arrow position left is positioned at top right corner (not centered vertically)

### ISSUE THREAD

**Issue by cortis** [teodorpatras/EasyTipView#147]
Hi Guys,

Specifying arrowPosition .left positions the tip view at top right corner but should be consistent with arrow position .right and center the tip vertically on the view.  

Fix:
Replace case .left in func computeFrame with:
case .left:
            xOrigin = refViewFrame.x + refViewFrame.width
            yOrigin = refViewFrame.center.y - contentSize.height / 2

Notes:
I tested the solution above and it works.

**Comment by teodorpatras** [comment]
Hi! Thanks for the information. Please feel free to open a Pull Request.

**Comment by cortis** [comment]
I normally would, but am too busy right now to do it.  It should be a dead simple fix on your end.
