### ISSUE TITLE
IBInspectable / IBDesignable support?

### ISSUE THREAD

**Issue by Ashu** [teodorpatras/EasyTipView#15]
Any plans for adding IBInspectable / IBDesignable support so that it becomes a bit easy for use in storyboard? Also it would be a good idea to support encoding / decoding by subclassing NSCoder.

**Comment by teodorpatras** [comment]
I think you miss the whole point of this control. ``EasyTipView`` is not meant to be used in storyboards or nib files (it's purpose is not like the one of a ``UILabel`` or ``UIButton``, it is more like a ``UIAlertView``). It is meant to be showed programmatically. If you want to customize it, you can use the ``Preferences`` structure.
