### ISSUE TITLE
Showing this to initial users

### ISSUE THREAD

**Issue by 1omarsaid** [teodorpatras/EasyTipView#153]
Is there a way that I can only show these tooltip views to a first time user? so that when they user uses the app the second time, the views are no longer there?

**Comment by 1omarsaid** [comment]
let launchedBefore = UserDefaults.standard.bool(forKey: "launchedBefore")
if launchedBefore {
print("Not first launch.")
} else {
print("First launch, setting UserDefault.")
UserDefaults.standard.set(true, forKey: "launchedBefore")
}

Customize the above to dismiss!!

**Comment by teodorpatras** [comment]
Yes, you can do that but your issue has nothing to do with the library. Store a boolean in `UserDefaults ` and this way you know if your user was presented with the tooltips or not. Cheers!
