### ISSUE TITLE
Bad Access Error with Versions 2.0.3 & 2.0.4 , 2.0.1 runs without problems (same code)

### ISSUE THREAD

**Issue by Skyb0rg** [teodorpatras/EasyTipView#162]
Hi,

if i use this Code:

    var pref = EasyTipView.Preferences()
        pref.drawing.font = UIFont.boldSystemFont(ofSize: 20)
        pref.drawing.textAlignment = .center
        pref.drawing.backgroundColor = UIColor.black.withAlphaComponent(0.8)
        pref.drawing.arrowPosition = .top
        
        pref.animating.dismissTransform = CGAffineTransform(translationX: 0, y: -100)
        pref.animating.showInitialTransform = CGAffineTransform(translationX: 0, y: -100)
        pref.animating.showInitialAlpha = 0
        pref.animating.showDuration = 0.5
        pref.animating.dismissDuration = 0.5
        pref.positioning.maxWidth = self.ContainerView.view.frame.width * 0.8
        
        EasyTipView.globalPreferences = pref

i get a bad access error for the last line.
if i remove this line i get bad access errors at:

     let newTipView = EasyTipView.init(text: text, preferences: pref, delegate: self)
     newTipView.show(animated: true, forView: tipForView, withinSuperview: tipView)

the first line here :(

if i use:
var test = EasyTipView.globalPreferences

i got bad access error, too.

Thank you

**Comment by teodorpatras** [comment]
I cannot reproduce your issue. I ran your code and it worked for me.

You shouldn't get bad access when ` EasyTipView.globalPreferences` because it's declared as public. 
`public static var globalPreferences = Preferences()`

I would say it's something else causing your badd access error.

**Comment by berdikhan-fave** [comment]
Same here, 2.0.1 has no issue, getting crash on 2.0.3 & 2.0.4.
`EasyTipView.show(animated: true, forView: tooltipView, withinSuperview: self.superview, text: text, preferences: preferences)` & 
`EasyTipView.globalPreferences = preferences` both lines are crashing

**Comment by Skyb0rg** [comment]
I think it has something to do with using this code multiple times in a small amount of time.
Moved the globalPreferences to viewdidload and could avoid the problem for now.
