### ISSUE TITLE
Custom contentView is always laid out with its frame origin at (0, 0)

### ISSUE THREAD

**Issue by jaltreuter** [teodorpatras/EasyTipView#166]
Code to reproduce this issue:

```
var tipPreferences = EasyTipView.globalPreferences
tipPreferences.drawing.arrowPosition = .bottom
tipPreferences.positioning.bubbleVInset = 14
let contentView = MyCustomTipContent()
EasyTipView.show(animated: true, forView: tipViewSource, withinSuperview: view, contentView: contentView, preferences: tipPreferences)
```

After the tip is presented, I would expect `contentView.frame.origin.y` to be 14 so that it's fully within the drawn bubble, but instead the y origin is 0 and the content is drawn partially outside (specifically above) the bubble.

It appears that this is an issue of the order in which EasyTipView sets the frame of the content view and when it adds the content view as a subview.  The frame is set in `arrange(withinSuperview:)` and _then_ it's added as a subview in `draw(_:)`.  For some reason the `addSubview(_:)` call causes the frame origin to reset to (0, 0) next time the view is laid out.

I've addressed this somewhat crudely in my own fork of this library: in `draw(_:)`, directly after `addSubview(_:)` I call `layoutIfNeeded` to immediately force the frame origin reset.  Then I manually set the frame.  https://github.com/jaltreuter/EasyTipView/commit/ec165127080a39bcb770165658376bd838fb4a8f

If my commit seems clean enough I can submit it as a pull request, but feel free to do your own investigation as it's possible there's a better solution.

**Comment by simformsolutions** [comment]
@jaltreuter can you please share code here as I'm also facing same issue

**Comment by koollhimanshu** [comment]
@jaltreuter can you please share the code I'm also facing same issue?

**Comment by jaltreuter** [comment]
@koollhimanshu see the link in my original comment

**Comment by jaltreuter** [comment]
Turns out I made a simple mistake in my original commit, causing the custom content to respect the bubble insets but not the content insets.  This commit corrects that issue: https://github.com/jaltreuter/EasyTipView/commit/59e6c5cdceb8d96b353f4c6a9d68a45d8dd41ddd

**Comment by ximenaperez** [comment]
I'm having trouble using a custom view with a large text inside the tooltip. I don't think the frame size is calculated correctly. I would like to do something similar to the maxWidth on the text, but with the view, and have the height be calculated in order of the width. Is that possible? If I set a width constraint to the view, the view looks ok and has the height I want, but without it, the tooltip isn't calculating it properly, and it's showing the entire text inside my view in one line. Any help is appreciated. Thanks :)

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
