### ISSUE TITLE
Wrong frame on portrait orientation

### ISSUE THREAD

**Issue by janselr** [teodorpatras/EasyTipView#17]
The issue only happens when the view controller open in portrait orientation, and after you make a little orientation changes the tip adjust to the right frame, is this something known ?

![image](https://cloud.githubusercontent.com/assets/2993852/13383873/ff13c376-de65-11e5-9196-1d346524fc4a.png)

**Comment by teodorpatras** [comment]
I need more insight in order to reproduce this issue.

**Comment by janselr** [comment]
The screenshot correspond to a navigation controller with a normal root view controller, with a black view at a bottom center. the controller is using auto layout and the devices was an iPhone 6, but I also tested on an emulator and also happens. after a put the device **FaceUp** the tip seem to adjust to its right position.

**Comment by teodorpatras** [comment]
still cannot reproduce, please post a gist
