### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by boborbt** [teodorpatras/EasyTipView#173]
Hi. With the recent addition of Swift Package Manager to Xcode, I was wondering if there is any chance that support for it is added to this awesome library.

**Comment by kamvoick** [comment]
any news on that?

**Comment by othyn** [comment]
Yeah, would love this!

**Comment by nacho4d** [comment]
I added a new Pull Request https://github.com/teodorpatras/EasyTipView/pull/193 today.  Until it is merged, feel free to use my fork.



https://github.com/nacho4d/EasyTipView/
2.0.7 or up is fine :)

<img width="742" alt="Screen Shot 2020-09-10 at 0 18 01" src="https://user-images.githubusercontent.com/111651/92618236-1c13e380-f2fb-11ea-83f9-192f5e823545.png">

**Comment by smamczak** [comment]
Please merge this into main repository

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
