### ISSUE TITLE
easyTipViewDidDismiss not called when declaring an EasyTipView as class variable

### ISSUE THREAD

**Issue by brettalcox** [teodorpatras/EasyTipView#18]
As the title says, in my class declaration I have a var helpTip : EasyTipView! and then perform some code in a function below. Whenever I dismiss the helpTip, either programmatically, or by clicking the tooltip itself, the function is never called. Is there anything I'm not doing?

**Comment by teodorpatras** [comment]
maybe you forgot to assign the delegate?

**Comment by brettalcox** [comment]
I assigned the delegate, but let me further explain my situation. I'm adding a tooltip to a button in the navigation bar. When you click the bar button, the tool tip will display, and when you click the button again, I programmatically dismiss the tool tip. I have a if == nil { show tool tip} and an else {dimiss tool tip} to deal with that logic. The issues lies when you dismiss the tooltip by clicking on it. For some reason, the delegate method is never called, so when i go to click the bar button again, I have to tap it twice, one to set the tooltip back to nil, and once more to display the tool tip.

**Comment by brettalcox** [comment]
Ahhhhh assigned the delegate wrong! All is good now!
