### ISSUE TITLE
tooltip height miscalculation

### ISSUE THREAD

**Issue by andeeliao** [teodorpatras/EasyTipView#183]
Hello! I'm running into an issue where when my tooltip has a right arrow, the height is a lot more than expected for the custom content view I've initialized it with. 

Here are the screenshots using the debugger. 
<img width="214" alt="Screen Shot 2020-02-07 at 11 33 09 AM" src="https://user-images.githubusercontent.com/9560524/74061012-fc50c180-499f-11ea-84d5-aae2d54a98f5.png">
<img width="200" alt="Screen Shot 2020-02-07 at 11 33 18 AM" src="https://user-images.githubusercontent.com/9560524/74061014-fd81ee80-499f-11ea-999e-6ab7d6815bdc.png">

Here are the logs where I've printed the frames:
```
contentView (-1.5, 3.5, 91.0, 25.5)
tooltip Optional((577.0, 18.75, 93.0, 32.5))
```

Here is how I am initializing the tooltip:
```
extension EasyTipView {
    
    convenience init?(contentView: TooltipView, arrowPosition: EasyTipView.ArrowPosition) {
        var preferences = EasyTipView.Preferences()
        preferences.drawing.backgroundColor = .yellow
        preferences.drawing.arrowPosition = arrowPosition
        preferences.positioning.contentVInset = 0
        preferences.positioning.contentHInset = 0
        preferences.animating.dismissDuration = 0.0
        self.init(contentView: contentView, preferences: preferences)
    }
}
```

Is there a way around this? It doesn't happen when I initialize with `arrowPosition = .bottom`. Any guidance would be appreciated!

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
