### ISSUE TITLE
Designated initializers restrictions in Xcode 11.4

### ISSUE THREAD

**Issue by javiermorgaz** [teodorpatras/EasyTipView#186]
Hi!

We did a rollback to version 2.0.1 because after migration to Xcode 11.4 the initializers we had access before are not available and doesn't allow us to subclass EasyTipView with the changes added in the last 2.0.4.

This is because a new restriction in Xcode 11.4 as you can see in the release notes:
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes

> Convenience initializer inheritance for subclasses defined outside the module that defines the base class now comes with additional restrictions. When these subclasses have a base class with non-public designated initializers, they no longer automatically inherit convenience initializers from their superclasses. To restore this automatic inheritance behavior, the base class must ensure that all of its designated initializers are public or open. (51249311)

Is there any chance to get back subclassing again?

Thanks.

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
