### ISSUE TITLE
Display tooltip inside UITextView at highlighted text

### ISSUE THREAD

**Issue by alamodey** [teodorpatras/EasyTipView#189]
Hi, I've just implemented EasyTipView in my app but I would like to display the tooltip at where the current highlighted text is. Can you show an example of how to implement this to improve usability? Thanks. 

![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-07-28 at 21 31 46](https://user-images.githubusercontent.com/55496019/88664927-2ac68280-d121-11ea-8a66-23c457f96d49.png)

**Comment by teodorpatras** [comment]
Please feel free to open a feature pull request.
