### ISSUE TITLE
How to dismiss tooltip when you change tabs?

### ISSUE THREAD

**Issue by alamodey** [teodorpatras/EasyTipView#190]
I'm using EasyTipView in an app that uses a tab bar controller, how do I dismiss the tooltip when I change tabs so it doesn't appear out of place?

![IMG_C7E3089761B7-1](https://user-images.githubusercontent.com/55496019/89179105-686c5500-d5d2-11ea-8da0-fd3b54fe489f.jpeg)

**Comment by sabiland** [comment]
I have the same issue, when I dismiss viewController -> parent, EasyTipView is still visible.

**Comment by dhirajRoundr** [comment]
You can dismiss tooltip in disappear method.
