### ISSUE TITLE
EasyTipView is not corrected to the correct position  when rotating the device on iPad

### ISSUE THREAD

**Issue by daidongon** [teodorpatras/EasyTipView#191]
Hello !

I passed the UIBarButtonItem instance to the show method of EasyTipView to display it.
Then I rotated the iPad and saw that EasyTipView was displayed in a place that had nothing to do with the UIBarButtonItem instance. (The UIBarButtonItem instance was previously set to navigationItem.rightBarButtonItem)

Apparently, the position was not updated by being guarded by the conditional expression of `if !isFrameValid(frame, forRefViewFrame: refViewFrame, withinSuperviewFrame: superviewFrame)` of EasyTipView method `fileprivate func arrange(withinSuperview superview: UIView)`.

**Comment by AlaeddineOuerteni** [comment]
Hello @daidongon,

Did you find any way to fix it ?

Thank you

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
