### ISSUE TITLE
How to hide tooltip in tableview cell while scrolling tableview 

### ISSUE THREAD

**Issue by dhirajRoundr** [teodorpatras/EasyTipView#194]
I have tried many ways but did not works for me. I am able to hide when close the view controller but can not hide while scrolling tableview.
Thanks in advance.

**Comment by priyankgandhi0** [comment]
use scrollviewdidscroll method  like this 

func scrollViewDidScroll(_ scrollView: UIScrollView) {
        self.tipView?.dismiss()
    }
