### ISSUE TITLE
Feature request - set timer for automated dismissal

### ISSUE THREAD

**Issue by mitchellporter** [teodorpatras/EasyTipView#23]
Hey, I love this library. API is simple and easy to use. Only feature that's missing for me is the ability to set a timer on the view and have it automatically dismiss itself. Thanks.

**Comment by ed-mejia** [comment]
+1

**Comment by mgiroux** [comment]
+1

**Comment by yigitserin** [comment]
I use it like this and it works fine:

        let tipView = EasyTipView(text: text, preferences: preferences)
        tipView.show(forView: sender, withinSuperview: self.view)
        
        
        let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC)))
        dispatch_after(delayTime, dispatch_get_main_queue()) {
            tipView.dismiss()
        }

**Comment by teodorpatras** [comment]
I don't think this is within the attributes of the view, to auto hide itself, but you could easily wrap it in an extension: https://gist.github.com/teodorpatras/d0c37bfbbc1425dec8f42ca41ba05796
