### ISSUE TITLE
For Obj-C

### ISSUE THREAD

**Issue by mypickles** [teodorpatras/EasyTipView#24]
Hi there,

This library really look great. But not sure if it is possible for to use for Obj-C project?

Cause I've tried to "pod install" it to my Obj-C project, and realized that inside EasyTipView.h only have 2 methods and not able for us to set text for it.

Hoping you can spend some minutes to help on this, appreciate it much.

**Comment by bkvirendra** [comment]
Yes same here, couldn't really use it with obj-c! :(

**Comment by gogozs** [comment]
I simply line by line copy (in Objective-C, for study purpose) from this project. if you are interested, check out https://github.com/gogozs/SZEasyTipView.

**Comment by teodorpatras** [comment]
Hi, thanks for the appreciation. Unfortunately `EasyTipView` is not intended to be used with Obj-C.
