### ISSUE TITLE
Support for attributed strings?

### ISSUE THREAD

**Issue by damirstuhec** [teodorpatras/EasyTipView#29]
That would be really nice, since we could then freely stylise the text in the tip view.

**Comment by hibernat** [comment]
I have added attributed text support, but pull request failed - xcpretty failed. Is anyone maintaining this repo?
https://github.com/teodorpatras/EasyTipView/pull/184

Forked repo is here: https://github.com/hibernat/EasyTipView/tree/attrString-content, check branch attrString-content

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
