### ISSUE TITLE
The tip view won't function right at the second time.

### ISSUE THREAD

**Issue by hulizhen** [teodorpatras/EasyTipView#30]
Everything was fine when I clicked a button to show the tip view the first time, as well as I tapped the tip view to dismiss it:
![image](https://cloud.githubusercontent.com/assets/2831422/15846970/8bd0ed24-2cb4-11e6-8aa2-218fe816bbf5.png)

Problem is that when you click the button to show the tip view again, odd thing happens:
![image](https://cloud.githubusercontent.com/assets/2831422/15846982/a93e6134-2cb4-11e6-94f6-b5ed54493f77.png)

Here's the demo which can reproduce the issue: [EasyTipViewDemo.zip](https://github.com/teodorpatras/EasyTipView/files/301908/EasyTipViewDemo.zip).

**Comment by teodorpatras** [comment]
Thank you for pointing this bug out. Fixed in https://github.com/teodorpatras/EasyTipView/commit/1cb0cbfdbf694b37bfe99c4d09d8312d87fbbc94.
