### ISSUE TITLE
Support for Swift 3 (pull request pending new branch)

### ISSUE THREAD

**Issue by kevinwo** [teodorpatras/EasyTipView#32]
I've created a fork with a 'swift-3.0' branch containing change with support for Swift 3.

https://github.com/kevinwo/EasyTipView/tree/swift-3.0

Test are still passing and the example app appears to run as expected on iOS 10. If the fork looks good and a new branch is created here, I'd be happy to submit a pull request. Please let me know if you have any thoughts or questions. Thanks!

**Comment by teodorpatras** [comment]
`swift-3.0` branch created. You are welcome to make a pr. Thanks for your support ✌️
