### ISSUE TITLE
easyTipViewDidDismiss not called when calling dismiss()

### ISSUE THREAD

**Issue by theolof** [teodorpatras/EasyTipView#33]
I expected easyTipViewDidDismiss to be called when doing
`self.tipView.dismiss()`
but it isn't.

I do that when the user taps an overlay.
easyTipViewDidDismiss is called when the user taps the tipView (so the delegate should be correct).

Is it an issue or am I holding it wrong?

**Comment by teodorpatras** [comment]
Delegation call hasn't been implemented in this case because you have the completion block that gets called after the view has been dismissed:

```
view.dismiss(withCompletion:{ _ in
     // code executed after the view has been dismissed
})
```

**Comment by theolof** [comment]
OK, so I have to call the same code as I do in easyTipViewDidDismiss.
I think it would have been cleaner to always do easyTipViewDidDismiss whenever the view has been dismissed, regardless of how it was dismissed.

It works though.

**Comment by teodorpatras** [comment]
Thanks for your insight, I'll make this feature available in next release.

**Comment by teodorpatras** [comment]
fyi version `0.2.1` has this fix applied

**Comment by theolof** [comment]
sweet!

**Comment by choujar** [comment]
I'm sorry, but I still can't work out how to perform actions when the user dismisses the tooltip by tapping on it (that seems like the default option, right?).

**Comment by choujar** [comment]
Hi folks, any update on this?

**Comment by theolof** [comment]
```
class TheViewController: UIViewController, EasyTipViewDelegate {
...
tipView = EasyTipView(text: "The text", preferences: preferences, delegate: self)
...
func easyTipViewDidDismiss(_ tipView: EasyTipView) {
...

```
That's my setup. When I click the tooltip, the function easyTipViewDidDismiss is called.
