### ISSUE TITLE
Showing tip for UIView elements that are not visible on screen (not visible for user)

### ISSUE THREAD

**Issue by neman** [teodorpatras/EasyTipView#34]
I have issues when showing tips for elements that are not visible on screen (view.window is nil)
Tips showed for current screen but not for uiview controls which are not visible for user.
When I scroll th screen, those tips are also scrolled up with screen. Is there some elegant solution for this problem, so I can put tips on proper position for those controls?

I tried to scroll up grammatically, and then show tips, but tips are still scrollable.

**Comment by teodorpatras** [comment]
I guess you have to show the tips inside the same superview as your other elements, the scrollview for instance.

**Comment by neman** [comment]
Ok, will try later and report the results.
