### ISSUE TITLE
EasyTipView not showing in superview.

### ISSUE THREAD

**Issue by perteadrian** [teodorpatras/EasyTipView#38]
So, I have did this in my viewDidLoad: 
```
EasyTipView.show(forView: self.shareBtnO,
                             withinSuperview: self.gradientView,
                             text: "Share",
                             preferences: tooltipPreferences ,
                             delegate: nil)
```
Preferences: 
```
var tooltipPreferences = EasyTipView.Preferences()
        tooltipPreferences.drawing.font = UIFont(name: "FaktPro-Normal", size: 16)!
        tooltipPreferences.drawing.foregroundColor = UIColor.whiteColor()
        tooltipPreferences.drawing.backgroundColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.1)
        tooltipPreferences.drawing.arrowPosition = EasyTipView.ArrowPosition.Top
        EasyTipView.globalPreferences = tooltipPreferences
``` 
but the the app crashes with error: 
precondition failed: The supplied superview <<UIView: 0x16d8d670; frame = (0 0; 600 600); autoresize = W+H; layer = <CALayer: 0x16d8d730>>> is not a direct nor an indirect superview of the supplied reference view <<UIButton: 0x16e79ff0; frame = (-23 -15; 46 30); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x16e7a2e0>>>. The superview passed to this method should be a direct or an indirect superview of the reference view. To display the tooltip within the main window, ignore the superview parameter.: file /Users/perte/Documents/GitHub/project/Pods/EasyTipView/Source/EasyTipView.swift, line 94

I tried self.shareBtnO.superview instead of self.gradientView . I can't let that parameter empty because otherwise the tooltip appears under the my gradient view, like here 
![screen shot 2016-07-11 at 19 31 03](https://cloud.githubusercontent.com/assets/15149863/16738367/0b215ca4-479e-11e6-9a71-b0adfa9c9678.png)

**Comment by teodorpatras** [comment]
I don't understand much from your view stack. What happens when you pass `self.shareBtnO.superview` to `withinSuperview:`? Same assertion get triggered?

**Comment by perteadrian** [comment]
yeah. Let me take a better stack view

**Comment by perteadrian** [comment]
![screen shot 2016-07-11 at 19 39 24](https://cloud.githubusercontent.com/assets/15149863/16738637/36dfe882-479f-11e6-8447-de8e43b3fef1.png)
Now U can see the UIButton I am referring and where the tooltip is made. I am able to run it beacuse the withinSuperview is empty.

**Comment by teodorpatras** [comment]
If you get that assertion, then this:

```
func viewHasSuperview (view: UIView, superview: UIView) -> Bool {
        if let sview = view.superview {
            if sview === superview {
                return true
            }else{
                return viewHasSuperview(sview, superview: superview)
            }
        }else{
            return false
        }
    }
```
returns false.  It's a pretty simple function that checks if a view is a distant superview for a targeted view. Check your view hierarchy maybe something isn't as it should.
