### ISSUE TITLE
If text is too short, arrow tip will be misplaced.

### ISSUE THREAD

**Issue by 2mittens** [teodorpatras/EasyTipView#4]
If the text contained in the tip view is too short, making the width of the tooltip too small compared to the width of the view target, the arrow tip will be displayed at far right.

To replicate the issue just give the C rectangle in the example a width of 80, and write inside the relative tooltip the word "Tip".

I'll also look into this in the next days if I have some free time.

Thank you!

**Comment by teodorpatras** [comment]
Thanks for pointing that out! Issue has been fixed.

**Comment by 2mittens** [comment]
Never had a time to thank you before! Now it's perfect, so thank you! 👍
