### ISSUE TITLE
Auto dismiss option?

### ISSUE THREAD

**Issue by rebenquito** [teodorpatras/EasyTipView#48]
Is there a way to set a tipView duration? (something like an auto dismiss after a established period)
Thank you for your work.

**Comment by teodorpatras** [comment]
you can just use `dispatch_after`

**Comment by abousaif56** [comment]
i am a beginner in swift, i think your easytipview is really good... i have installed the easytipview in my project and is working fine, no problems... i click on it and it goes away..
but also i need to dismiss it automatically (say after 5 seconds) as mentioned above by rebenquito above.. can you please explain into more details for me how to use the dispatch_after , i tried many ways but was unsuccessful.. i use swift 4, appreciate your help. thanks
