### ISSUE TITLE
maxWidth does not work when I try setup width of bubble message

### ISSUE THREAD

**Issue by avshiyanov** [teodorpatras/EasyTipView#51]

**Comment by teodorpatras** [comment]
can you provide an example?

**Comment by avshiyanov** [comment]
// EasyTipView
        var preferences = EasyTipView.Preferences()
        preferences.drawing.font = UIFont.systemFontOfSize(15)
        preferences.drawing.foregroundColor = UIColor.whiteColor()
        preferences.drawing.backgroundColor = Colors.blueColor!
        preferences.positioning.maxWidth = 290
        EasyTipView.globalPreferences = preferences

**Comment by avshiyanov** [comment]
I think it's because Dialog width depends on text size

**Comment by teodorpatras** [comment]
This width is not 100% fixed, it is the preferred bubble width which is used when getting the size of the text in the bubble.
