### ISSUE TITLE
Error - Expressions are not allowed at the top level

### ISSUE THREAD

**Issue by filipecmsf** [teodorpatras/EasyTipView#55]
Hi,

I just installed the lib but I'm always getting a few errors inside the lib.

The first error returned is "Expressions are not allowed at the top level" at line 151.

I've installed version 1.0.2 using cocoapods

Am I missing something?
![captura de tela 2016-09-16 as 00 13 38](https://cloud.githubusercontent.com/assets/2207381/18574358/c2af7b02-7ba2-11e6-942e-2e5c97902d55.png)

thanks,

Filipe

**Comment by teodorpatras** [comment]
Hey, what Xcode and what version of Swift you are using?

**Comment by filipecmsf** [comment]
I'm using swift 2.2 and Xcode 7.3

**Comment by teodorpatras** [comment]
Version `1.0.2` is updated for Xcode 8. I recommend you to use the previous version `1.0.1` since the only difference is the Xcode 8 support.
