### ISSUE TITLE
Swift 3 errors

### ISSUE THREAD

**Issue by theolof** [teodorpatras/EasyTipView#61]
I have Xcode 8 and trying to convert my project to Swift 3.

In my Podfile:
`pod 'EasyTipView', '~> 1.0.2'`

When I build the project, I get:

`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

What am I doing wrong?

**Comment by potmo** [comment]
I got the same issue. You can work around it in your Podfile by adding this.
 But it would be nice if the project file was updated.
```# Force swift 3 config
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end```

**Comment by teodorpatras** [comment]
Hey guys, can you walk me through your problem? I keep on getting these issues on several projects but for me it does not reproduce.

Steps I followed:
1. Create a new Xcode project.
2. run `pod init`
3. add `pod 'EasyTipView', '~> 1.0.2'` to the Podfile
4. run `pod install`
5. open `*.xcworkspace` and import the library where you want to use it.

It all worked seamlessly for me.

**Comment by theolof** [comment]
My steps:
1. Open existing Swift 2.2 project
2. Use the migration tool in Xcode 8 (only on my code, not on the pods)
3. Be frustrated by the migration tool and Xcode in general
4. pod install
5. build project
6. Error message as described

It wasn't only EasyTipView, it happened for Material as well (https://github.com/CosmicMind/Material).

**Comment by philhudson91** [comment]
Getting this same error too :/

**Comment by philhudson91** [comment]
When I use the following code I get:

```# Force swift 3 config
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end```

`Module file was created by a new version of the compiler...` error. Not sure how to get around this.

**Comment by teodorpatras** [comment]
If the fix is on the framework's side, then you're welcome to open a PR with the fixes.

**Comment by philhudson91** [comment]
This is still an issue?

**Comment by teodorpatras** [comment]
Some people use this to get around your issue:

```
# Force swift 3 config
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
```

I cannot find anything wrong on the library's side, it works with a brand new Swift 3 project, but when you have a Swift 2.x project which you migrate to Swift 3 using Xcode, somehow the pod gets messed up. Maybe this is an issue concerning cocoapods?

**Comment by philhudson91** [comment]
Still looking at this regarding fixes (literally investigating right now).

Is 1.0.2 the latest?

**Comment by teodorpatras** [comment]
Yes, 1.0.2 is the latest. If you find something on how to fix this problem from the library's side, you can open a PR.

**Comment by philhudson91** [comment]
When using the force swift 3 workaround - Xcode complains saying the module was created by a newer version of the compiler.
