### ISSUE TITLE
Reference to the EasyTipView created

### ISSUE THREAD

**Issue by LukaszGrela** [teodorpatras/EasyTipView#65]
Is there a way to get the EasyTipView instance created with show method? E.g. to store it so later I can close them all if more than one on screen?

**Comment by LukaszGrela** [comment]
I guess the solution is to not use `EasyTipView.show` but instantiate it directly:) but anyway it would be convenient if static `show` would return created instance.

**Comment by teodorpatras** [comment]
This is the reason the API exposes to ways of showing the tooltip. Either the static method in case you don't care about the instance being shown, or you instantiate it if you need the instance.
