### ISSUE TITLE
Support for Objective-C?

### ISSUE THREAD

**Issue by danpe** [teodorpatras/EasyTipView#66]
The `EasyTipView/EasyTipView-Swift.h` that is being compiled only supports:

`@property (nonatomic, strong) UIColor * _Nullable backgroundColor;`

`- (void)showWithAnimated:(BOOL)animated forItem:(UIBarItem * _Nonnull)item withinSuperView:(UIView * _Nullable)superview;`

`- (void)showWithAnimated:(BOOL)animated forView:(UIView * _Nonnull)view withinSuperview:(UIView * _Nullable)superview;`

`- (void)dismissWithCompletion:(void (^ _Nullable)(void))completion;`

It's impossible to even set the `text` or `description` of the tooltip..

**Comment by roblav96** [comment]
Some support for `obj-c` would be ballin 🍰

**Comment by asadali737** [comment]
Waiting for Objective-C support...

**Comment by nitishmakhija** [comment]
Did someone say Objective-C support 
https://github.com/nitishmakhija/EasyTipView

**Comment by roblav96** [comment]
@nitishmakhija 🌮

**Comment by nitishmakhija** [comment]
Should close this thread 👍🏻
