### ISSUE TITLE
Dismiss EasyTipView when click outside

### ISSUE THREAD

**Issue by andrey-lisovskiy** [teodorpatras/EasyTipView#76]
I have an app with navigationBar and tabBar. What I want is to dismiss EasyTipView when user clicks anywhere outside of the tip. How can it be implemented?

**Comment by crazypigs** [comment]
same any help would be great.

**Comment by crazypigs** [comment]
http://stackoverflow.com/questions/28197079/swift-addsubview-and-remove-it 
check this out. you can use touch began function with a tag for the view :)

**Comment by swami-108** [comment]
Just add a gesture in viewDidLoad:
let gesture = UITapGestureRecognizer(target: self, action:  #selector (self.handleTapAnywhere))
self.view.addGestureRecognizer(gesture)

In handleTapAnywhere(), dismiss the tip.

**Comment by crazypigs** [comment]
Hey Swami-108 ! how do you grab the tip view without having a pointer to it? 
In a method i do this to add view to a button in a table:
```
 EasyTipView.show(forView: sender,
                         withinSuperview: self.navigationController?.view,
                         text: popupText,
                         preferences: preferences,
                         delegate: self)
```
My guess is that i try and find the button that the view tip belongs to and the iterate through its subviews to get the tip view?

I've been stuck on this for ages now :(

**Comment by crazypigs** [comment]
Ok so i got a solution to this but it required me to edit the source code Easytipview. 

`/**
     Presents an EasyTipView pointing to a particular UIView instance within the specified superview
     
     - parameter animated:    Pass true to animate the presentation.
     - parameter view:        The UIView instance which the EasyTipView will be pointing to.
     - parameter superview:   A view which is part of the UIView instances superview hierarchy. Ignore this parameter in order to display the EasyTipView within the main window.
     - parameter text:        The text to be displayed.
     - parameter preferences: The preferences which will configure the EasyTipView.
     - parameter delegate:    The delegate.
     */
    public class func show(animated: Bool = true, forView view: UIView, withinSuperview superview: UIView? = nil, text:  String, preferences: Preferences = EasyTipView.globalPreferences, delegate: EasyTipViewDelegate? = nil) -> EasyTipView{
        
        let ev = EasyTipView(text: text, preferences: preferences, delegate: delegate)
        ev.show(animated: animated, forView: view, withinSuperview: superview)
        
        return ev
    }`

Bascially i made it return the tip view so i can make a reference to it to be manipulated later.

**Comment by ADevelopStudio** [comment]
simplest (for me) idea was to create custom TapGestureRecogniser for the EasyTipView's superview :
```
class TapToDismissEasyTip: UITapGestureRecognizer {
    var easyTipView: EasyTipView? = nil
    var superView: UIView? = nil
    
    func set(easyTipView: EasyTipView?, superView: UIView?) {
        self.easyTipView = easyTipView
        self.superView = superView
        self.numberOfTouchesRequired = 1
        superView?.addGestureRecognizer(self)
        self.addTarget(self, action: #selector(self.dismiss))
    }
    
    @objc func dismiss()  {
        easyTipView?.dismiss(withCompletion: {
            self.superView?.removeGestureRecognizer(self)
        })
    }
}

```

and add it to **show** func  so:

```
    public class func show(animated: Bool = true, forView view: UIView, withinSuperview superview: UIView? = nil, text:  String, preferences: Preferences = EasyTipView.globalPreferences, delegate: EasyTipViewDelegate? = nil){
        
        let ev = EasyTipView(text: text, preferences: preferences, delegate: delegate)
        ev.show(animated: animated, forView: view, withinSuperview: superview)
        TapToDismissEasyTip().set(easyTipView: ev, superView: superview)
    }

```

**Comment by rouxbuciu** [comment]
@ADevelopStudio Not sure how your solution works as I tried it and it doesn't dismiss the view.
