### ISSUE TITLE
How to work with tableView cell

### ISSUE THREAD

**Issue by black-lotus** [teodorpatras/EasyTipView#78]
I tried to create tooltip inside tableview cell component, but... the position mess up after tableView is scrolled or reloaded..

is there any solution for this ?

Thank you in advance
Nice Library

**Comment by kingalione** [comment]
same here. I think it has to do with the auto-layout constrains

**Comment by znittzel** [comment]
Same for me also

**Comment by fusionbeam** [comment]
+1

**Comment by gerchicov-bp** [comment]
I need too. At least for table which is not scrolling

**Comment by iMacHumphries** [comment]
```
private func showTip(on cell: UITableViewCell) {
        EasyTipView.show(animated: true, forView: cell, withinSuperview: tableView, text: "This worked for me 🤷‍♂️")
    }
```

**Comment by failynsedik** [comment]
> ```
> private func showTip(on cell: UITableViewCell) {
>         EasyTipView.show(animated: true, forView: cell, withinSuperview: tableView, text: "This worked for me 🤷‍♂️")
>     }
> ```

Did you not experience any tooltip positioning bugs while the tableview is reloading?
