### ISSUE TITLE
Is there a simple way to make arrow position left or right? (in addition to current top or left) 

### ISSUE THREAD

**Issue by dhsu210** [teodorpatras/EasyTipView#8]
Am trying to implement this in a tableviewcell, but the arrow position of top or bottom ends up partially layered underneath neighboring cells due to the structure of the tableview.

**Comment by teodorpatras** [comment]
The nicest thing about EasyTipView is that it can be displayed within a view but pointing to an element in one of its subviews. Have you tried passing ``nil`` to the ``superview``? There is no support for side arrow at this moment.

**Comment by dhsu210** [comment]
Yeah I have tried the superview, but because this tableviewcell is clickable, it ends up leaving the "tip" as a residue once the user has moved out of the tableview, which, ideally, I would like to have disappear.

**Comment by dhsu210** [comment]
Nevermind, I went one more superview level and it seems to be working great! Thanks a lot!
