### ISSUE TITLE
error: Cannot extract bundle from...

### ISSUE THREAD

**Issue by asowers1** [teodorpatras/EasyTipView#80]
I'm having an issue where I can integrate and link EasyTipView via _Carthage_ with no problem, but when I go to produce an ipa for enterprise deployment with bitcode enabled, I'm receiving this error message from the archive exporter:

> Failed to verify bitcode in EasyTipView.framework/EasyTipView:
> error: Cannot extract bundle from /var/folders/p8/hn20mcb936qgc931vmx35tj00000gn/T/XcodeDistPipeline.dHP/Root/Payload/Spoke.app/Framework…

<img width="598" alt="screen shot 2017-03-08 at 3 31 25 pm" src="https://cloud.githubusercontent.com/assets/6819186/23722684/557ca816-0414-11e7-88cf-308224d37513.png">

Does anyone have any suggestions for making the ipa tool play nice with EasyTipView and bitcode in this context?

**Comment by asowers1** [comment]
Fixed the issue on my end. Someone on our team forgot to add EasyTipView to our `Copy Frameworks Script` in Build Phases.

**Comment by virendra656** [comment]
What did you do exactly please tell me

**Comment by omidrezaaa** [comment]
@asowers1  could you tel me how you can solve it?

**Comment by omidrezaaa** [comment]
@asowers1 could you explain more?
