### ISSUE TITLE
isCurrentlyShown boolean

### ISSUE THREAD

**Issue by nishantshrestha** [teodorpatras/EasyTipView#85]
Is there a way to know whether a tooltip is currently being shown or not?

I have a button, which when pressed shows a tip view. I'm noticing that multiple tip views gets added when .showInView is called. Would be handy to dismiss the tip view, if it's already shown.

Love the library otherwise. 👍

**Comment by herrkaefer** [comment]
@nishantshrestha The following method works for me:
```swift
if tipView.superview != nil { // the tipView is currently shown
    tipView.dismiss()
} 
else { 
    tipView.show(forView: sender)
}
```
