### ISSUE TITLE
Programmatically created Navigation Items

### ISSUE THREAD

**Issue by thejourneydude** [teodorpatras/EasyTipView#9]
I've programmatically created a right bar button item. When I run        
        
        EasyTipView.showAnimated(true,
            forView: navigationItem.rightBarButtonItem,
            withinSuperview: self.navigationController?.view,
            text: "Tip view inside the navigation controller's view. Tap to dismiss!",
            preferences: preferences,
            delegate: self)
        
The error states I can't convert the UIBarButtonItem to UIView. Obviously if I had an IBOutlet it would work but I created this bar button item programmatically. How can I get this to work for my situation?

**Comment by ExeRhythm** [comment]
Sorry for late response (5 years). Try this: `navigationItem.rightBarButtonItem.view`
