### ISSUE TITLE
'shared' is unavailable

### ISSUE THREAD

**Issue by ConcepterSolutions** [teodorpatras/EasyTipView#91]
Swift 3.0, Xcode 8.3.1, latest cocoapods

_EasyTipView.swift, line: 96_
`let superview = superview ?? UIApplication.shared.windows.first!`

> Project/Pods/EasyTipView/Source/EasyTipView.swift:96:52: 'shared' is unavailable: Use view controller based solutions where appropriate instead.

Also my project contains Widget extensions

**Comment by pchernovolenko** [comment]
Any update on this? Have the same error when using Widget extensions

**Comment by black-lotus** [comment]
I got same error
Have you guys solved this ?

**Comment by CodingAleCR** [comment]
You should go to the Pod Project definitions, select EasyTipView on the pod project, go to Build Settings and mark "Require Only App-Extension-Safe API"  as No. I don't know why it happens, I think it has to do with outdated Swift projects by I am not sure. This should, however, workaround the issue.
