### ISSUE TITLE
Typo in function signature

### ISSUE THREAD

**Issue by Eckelf** [teodorpatras/EasyTipView#98]
There is a typo in a function signature, see below:

```swift
public func show(animated: Bool = true, forItem item: UIBarItem, withinSuperView superview: UIView? = nil)
```

Notice the upper case 'View' in 'withinSuperView'. All other signatures write it as 'Superview', e.g.:

```swift
public func show(animated: Bool = true, forView view: UIView, withinSuperview superview: UIView? = nil)
```

It's not a big issue, however it has caused confusion when manually writing related code. Changing the signature would break existing code so maybe it's not worth the trouble.

**Comment by teodorpatras** [comment]
Would've been easier to open a PR, but thanks.
